version: "3"
services:
  server:
    platform: linux/amd64
    container_name: server
    env_file:
    - .env
    build:
      dockerfile: Dockerfile
      context: .
      target: runner
    ports:
      - "3000:3000"
    restart: always
    command: "server" 
