version: "3"
services:
  test_database:
    container_name: test_database
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5435:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: always

  server:
    platform: linux/amd64
    container_name: server
    env_file:
    - .env
    environment:
      DATABASE_HOST: test_database
      HOST: "0.0.0.0"
    build:
      dockerfile: Dockerfile
      context: .
      target: runner
    ports:
      - "3000:3000"
    restart: always
    links:
      - "test_database:test_database"
    depends_on:
      - test_database
    command: "server" 
