# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testdbconn
  namespace: default
  labels:
    app: testdbconn
spec:
  selector:
    matchLabels:
      app: testdbconn
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: testdbconn
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name: testdbconn
        image: testdbconn.azurecr.io/testconnectdb2:1.0.1
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        env:
        - name: ACCEPT_EULA
          value: "Y"
        ports:
        - containerPort: 80
          name: testdbconn
      restartPolicy: Always

